name: super-index
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - matplotlib
  - pandas=2.1.0
  - nextflow=23.10.1
  - anndata
  - dask
  - zarr
  - wiggletools
  - ucsc-bedgraphtobigwig
  - ucsc-bigwigtobedgraph
  - scikit-learn
  - umap-learn
  - seaborn
  - tmux
  - python=3.9
  - datatable
  - statsmodels
  - scipy
  - bedops
  - pysam=0.19.1
  - pyfaidx
  - r-essentials
  - samtools=1.15.1
  - ucsc-bedtobigbed
  - r
  - r-reticulate
  - r-catools
  - subread
  - bioconductor-deseq2
  - bioconductor-variancepartition
  - bioconductor-rhdf5
  - rpy2
  - tqdm
  - h5py
  - pip
prefix: /home/sabramov/miniconda3/envs/super-index
